file(READ "${TEMPLATE}" TEMPLATE_CONTENT)
file(READ "${HELP_FILE}" HELP_CONTENT)
string(REPLACE "__HELP__" "${HELP_CONTENT}" FINAL_CONTENT "${TEMPLATE_CONTENT}")
file(WRITE "${OUTPUT}" "${FINAL_CONTENT}")